[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
eth_rpc_url = "${SEPOLIA_RPC_URL}"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/",
]

# Solidity compiler settings
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
verbosity = 2
fuzz_runs = 256
fuzz_max_test_rejects = 65536

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = []

# Formatter settings
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"

# RPC endpoints
[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/rBgXMI1K1DTe3cHIew_X3VV1EcpMlzsp"

# Etherscan API keys
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }